### ISSUE TITLE
Legacy import from ODK Aggregate to WAStD - stragglers

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#349]
A last batch of records was uploaded to ODK Aggregate (ODKA) from a third party tablet at Cape Lambert. Since the last import from ODKA, WAStD was developed further, and the data model has changed. Only the new import from ODK Central was upgraded, while the legacy import from ODKA was not.

The legacy import (ODK-A to WAStD) now needs to be upgraded to the latest changes to LoggerEnc in order to allow upload of the last few records.

- [x] ETA: 20 to 40 hours development work.
- [ ] Outcome: The last records are imported into WAStD, then we can sunset ODK Aggregate instance.
- [ ] Follow up: Liaise with data collectors to QA data and upgrade tablet.

**Comment by florianm** [comment]
In WAStD, logger encounters have been changed to logger observations.
The current (outdated) import script falls over the now missing logger encounter model and needs to be updated to attach a logger observation to the parent encounter.

Current error when running "Import ODKA" against local master:
```
NameError: name 'handle_loggerencounter' is not defined
[ERROR] Internal Server Error: /tasks/import-odka/
Traceback (most recent call last):
...
  File "/home/florianm/projects/wastd/wastd/observations/views.py", line 57, in import_odka_view
    msg = import_odka.now()
  File "/home/florianm/projects/wastd/wastd/observations/tasks.py", line 47, in import_odka
    utils.import_all_odka(path=path)
  File "/home/florianm/projects/wastd/wastd/observations/utils.py", line 5471, in import_all_odka
    tt36=[import_odka_tt044(x) for x in downloaded_data("build_Track-or-Treat-0-36_1508561995", path)],
  File "/home/florianm/projects/wastd/wastd/observations/utils.py", line 5471, in <listcomp>
    tt36=[import_odka_tt044(x) for x in downloaded_data("build_Track-or-Treat-0-36_1508561995", path)],
  File "/home/florianm/projects/wastd/wastd/observations/utils.py", line 5010, in import_odka_tt044
    handle_loggerencounter(end, media, data)
NameError: name 'handle_loggerencounter' is not defined
```
