### ISSUE TITLE
LineTransectEnc need 3D support or 2D data

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#355]
## Reproducible example

etlTurtleNesting import of LineTxEnc fails with 
```
[INFO] [API][create] Fetching existing Encounter records...

[INFO] [API][create] Found 0 existing Encounter records: 0 to retain, 0 to update

[INFO] [API][create] Found 1 records without matching Encounter.

[INFO] [API][create] Skipping 0 QA'd records

[DEBUG] [API][create] Skipping QA'd records: []

[INFO] [API][create] Done sorting records: 1 refused (create Encounter first), 0 to retain, 0 to update, 0 to create.

[INFO] [API][create] Finished.

[INFO] Refused 1, retained 0, updated 0, created 0 records.

[INFO] [API][create] found batch of 2 records, creating/updating...

[INFO] [API][create] Fetching existing records...

[INFO] [API][create] Done fetching existing records.

[INFO] [API][create] Sorting records into retain/update/create...

[INFO] [API][create] Skipping 0 locally changed records

[DEBUG] [API][create] Skipping locally changed records: []

[INFO] [API][create] Done sorting records: 0 to retain, 0 to update, 2 to create.

[INFO] [API][create] Creating records...

[INFO] {'source': 'odk', 'source_id': 'uuid:4a602009-1e2a-441f-a559-7693e83eb7a4', 'where': 'POINT (115.88331732899 -31.9954854903555)', 'location_accuracy': '10', 'when': '2020-10-29T15:53:31+0800', 'transect': 'LINESTRING Z (115.8833 -31.99549 0, 115.8837 -31.99389 0, 115.8856 -31.99555 0)', 'reporter_id': 4, 'observer_id': 4}

[INFO] {'source': 'odk', 'source_id': 'uuid:4a602009-1e2a-441f-a559-7693e83eb7a4', 'where': 'POINT (115.88331732899 -31.9954854903555)', 'location_accuracy': '10', 'when': '2020-10-29T15:53:31+0800', 'transect': 'LINESTRING Z (115.8833 -31.99549 0, 115.8837 -31.99389 0, 115.8856 -31.99555 0)', 'reporter_id': 4, 'observer_id': 4}

[ERROR] Internal Server Error: /api/1/line-transect-encounters/

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 559, in get_or_create

    return self.get(**kwargs), False

  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get

    raise self.model.DoesNotExist(

wastd.observations.models.LineTransectEncounter.DoesNotExist: LineTransectEncounter matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute

    return self.cursor.execute(sql, params)

psycopg2.errors.InvalidParameterValue: Geometry has Z dimension but column does not

```

**Comment by florianm** [comment]
* WAStD LineTxEnc.transect updated to 3 dimensions.
* etlTurtleNesting re-run with update = TRUE.
* The two failing records from above are now imported.
Looks like this fix works.
