### ISSUE TITLE
Survey Detail View

### ISSUE THREAD

**Issue by florianm** [dbca-wa/wastd#358]
## Problem

QA operators want to know some details which are too computationally intensive to include in a list view.
* Details of duplicate surveys
* Linked encounters, each with a link to Encounter details (including Encounter history - previously linked Encounters)
* Locations: start, end, on a map with WAStD sites overlaid

## Feature

Survey detail page

**Comment by florianm** [comment]
First version deployed.
Some ISE: https://wastd.dbca.wa.gov.au/observations/surveys/8985/
```
IsADirectoryError: [Errno 21] Is a directory: '/usr/src/app/wastd/templates'

[ERROR] Internal Server Error: /observations/surveys/8985/

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response

    response = self.process_exception_by_middleware(e, request)

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response

    response = response.render()

  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render

    self.content = self.rendered_content

  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content

    return template.render(context, self._request)

  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render

    return self.template.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render

    return self._render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render

    return self.nodelist.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 936, in render

    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated

    return self.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render

    return compiled_parent._render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render

    return self.nodelist.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 936, in render

    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated

    return self.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render

    result = block.nodelist.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 936, in render

    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated

    return self.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 209, in render

    nodelist.append(node.render_annotated(context))

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated

    return self.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 176, in render

    template = context.template.engine.get_template(template_name)

  File "/usr/local/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template

    template, origin = self.find_template(template_name)

  File "/usr/local/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template

    template = loader.get_template(name, skip=skip)

  File "/usr/local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 53, in get_template

    template = super().get_template(template_name, skip)

  File "/usr/local/lib/python3.8/site-packages/django/template/loaders/base.py", line 24, in get_template

    contents = self.get_contents(origin)

  File "/usr/local/lib/python3.8/site-packages/django/template/loaders/cached.py", line 22, in get_contents

    return origin.loader.get_contents(origin)

  File "/usr/local/lib/python3.8/site-packages/django/template/loaders/filesystem.py", line 23, in get_contents

    with open(origin.name, encoding=self.engine.file_charset) as fp:

IsADirectoryError: [Errno 21] Is a directory: '/usr/src/app/wastd/templates'

['Internal Server Error: /observations/surveys/8985/', '  File "django/core/handlers/exception.py", line 34, in inner', '  File "django/core/handlers/base.py", line 145, in _get_response', '  File "django/core/handlers/base.py", line 143, in _get_response', '  File "django/template/response.py", line 105, in render', '  File "django/template/response.py", line 83, in rendered_content', '  File "django/template/backends/django.py", line 61, in render', '  File "django/template/base.py", line 171, in render', '  File "django/template/base.py", line 163, in _render', '  File "django/template/base.py", line 936, in render', '  File "django/template/base.py", line 903, in render_annotated', '  File "django/template/loader_tags.py", line 150, in render', '  File "django/template/base.py", line 163, in _render', '  File "django/template/base.py", line 936, in render', '  File "django/template/base.py", line 903, in render_annotated', '  File "django/template/loader_tags.py", line 62, in render', '  File "django/template/base.py", line 936, in render', '  File "django/template/base.py", line 903, in render_annotated', '  File "django/template/defaulttags.py", line 209, in render', '  File "django/template/base.py", line 903, in render_annotated', '  File "django/template/loader_tags.py", line 176, in render', '  File "django/template/engine.py", line 143, in get_template', '  File "django/template/engine.py", line 125, in find_template', '  File "django/template/loaders/cached.py", line 53, in get_template', '  File "django/template/loaders/base.py", line 24, in get_template', '  File "django/template/loaders/cached.py", line 22, in get_contents', '  File "django/template/loaders/filesystem.py", line 23, in get_contents']
```

**Comment by florianm** [comment]
Some templates still missing: 
https://wastd.dbca.wa.gov.au/observations/surveys/7968/
https://wastd.dbca.wa.gov.au/observations/surveys/8013/
